- name: Remove "{{ item }}"
  hosts: "{{ group }}"
  remote_user: gooroom
  tasks:
  - name: 1. Remove "{{ item }}"
    become: yes
    become_method: sudo
    apt: name="{{ item }}" state=absent autoremove=yes
