- name: List
  hosts: "{{ group }}"
  remote_user: gooroom
  tasks:
  - name: 1. Upgradable
    become: yes
    become_method: sudo
    command: apt-get update -s | grep -v Conf
    register: out

  - debug: var=out.stdout_lines
