- name: List
  hosts: "{{ group }}"
  remote_user: gooroom
  tasks:
  - name: 1. Upgradable
    become: yes
    become_method: sudo
    script: /srv/upgradable.sh
    register: out

  - debug: var=out.stdout_lines
