- name: List
  hosts: "{{ group }}"
  remote_user: gooroom
  tasks:
  - name: 1. Upgradable
    become: yes
    become_method: sudo
    command: printf "$(apt-get upgrade -s | grep -v ^Conf)"
    register: out

  - debug: var=out.stdout_lines
